---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: latest

inputs:
  - name: vault-proxy-code

outputs:
  - name: vault-proxy

run:
  path: vault-proxy-code/ci/build.sh

